version: 2.1

jobs:
  install_deps:
    working_directory: ~/saulo.dev
    docker:
      - image: circleci/node:12.14.1 # the primary container, where your job's commands are run
    steps:
      - checkout
      - restore_cache: # special step to restore the dependency cache
          # Read about caching dependencies: https://circleci.com/docs/2.0/caching/
          key: dependency-cache-{{ checksum "yarn.lock" }}
      - run:
          name: yarn installing things
          command: yarn install
      - save_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules

  # how to add correct env vars?
  build:
    working_directory: ~/saulo.dev
    docker:
      - image: circleci/node:12.14.1
    steps:
      - checkout
      - restore_cache: # special step to restore the dependency cache
          # Read about caching dependencies: https://circleci.com/docs/2.0/caching/
          key: dependency-cache-{{ checksum "yarn.lock" }}
      - run: # run tests
          name: build stuff
          command: yarn blog:build
      - save_cache:
          key: build-{{ checksum "yarn.lock" }}
          paths:
            - ./packages/blog/public
  lint:
    working_directory: ~/saulo.dev
    docker:
      - image: circleci/node:12.14.1
    steps:
      - checkout
      - restore_cache: # special step to restore the dependency cache
          # Read about caching dependencies: https://circleci.com/docs/2.0/caching/
          key: dependency-cache-{{ checksum "yarn.lock" }}
      - run:
          name: lint js + ts
          command: yarn lint

  deploy:
    working_directory: ~/saulo.dev
    docker:
      - image: banst/awscli:1.18.0
    environment:
      BUCKET_NAME: saulo.dev
      BUCKET_REGION: us-east-1
    steps:
      - checkout
      - restore_cache:
          key: build-{{ checksum "yarn.lock" }}
      - run:
          name: Deploy to s3!
          command: aws s3 sync packages/blog/public s3://$BUCKET_NAME --region=$BUCKET_REGION --delete

  # orbs:
  #   aws-s3: circleci/aws-s3@1.0.15
#   lint:
#     docker:
#       - image: circleci/node:12.14.1
#     steps:
#       - restore_cache: # Restores the cached dependency.
#           key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
#       - run:
#           name: Running lint
#           command: yarn lint

workflows:
  version: 2
  test_build_and_deploy:
    jobs:
      - install_deps
      - build:
          requires:
            - install_deps
      - lint:
          requires:
            - install_deps
      - deploy:
          requires:
            - build
            - lint
          filters:
             branches:
               only: master # Only deploy when the commit is on the Master branch
