version: 2.1

jobs:
  install_deps:
    working_directory: ~/saulo.dev
    docker:
      - image: circleci/node:12.14.1 # the primary container, where your job's commands are run
    steps:
      - checkout
      - restore_cache: # special step to restore the dependency cache
          # Read about caching dependencies: https://circleci.com/docs/2.0/caching/
          key: dependency-cache-{{ checksum "yarn.lock" }}
      - run:
          name: yarn installing things
          command: yarn install
      - save_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules

  # how to add correct env vars?
  build:
    working_directory: ~/saulo.dev
    docker:
      - image: circleci/node:12.14.1
    steps:
      - checkout
      - restore_cache: # special step to restore the dependency cache
          # Read about caching dependencies: https://circleci.com/docs/2.0/caching/
          key: dependency-cache-{{ checksum "yarn.lock" }}
      - run: # run tests
          name: build stuff
          command: yarn blog:build

  lint:
    working_directory: ~/saulo.dev
    docker:
      - image: circleci/node:12.14.1
    steps:
      - checkout
      - restore_cache: # special step to restore the dependency cache
          # Read about caching dependencies: https://circleci.com/docs/2.0/caching/
          key: dependency-cache-{{ checksum "yarn.lock" }}
      - run:
          name: lint js + ts
          command: yarn lint

  deploy:
    working_directory: ~/saulo.dev
    docker:
      - image: circleci/node:12.14.1
    steps:
      - run:
          name: Deploying!
          command: echo "Deploying :)"

  # orbs:
  #   aws-s3: circleci/aws-s3@1.0.15
#   lint:
#     docker:
#       - image: circleci/node:12.14.1
#     steps:
#       - restore_cache: # Restores the cached dependency.
#           key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
#       - run:
#           name: Running lint
#           command: yarn lint

workflows:
  version: 2
  build_and_test:
    jobs:
      - install_deps
      - build:
          requires:
            - install_deps
      - lint:
          requires:
            - install_deps
      - deploy:
          requires:
            - build
            - lint