version: 2.1
jobs:
  build:
    working_directory: ~/saulo.dev
    docker:
      - image: circleci/node:12.14.1 # the primary container, where your job's commands are run
    steps:
      - checkout
      - restore_cache: # special step to restore the dependency cache
          # Read about caching dependencies: https://circleci.com/docs/2.0/caching/
          key: dependency-cache-{{ checksum "yarn.lock" }}
      - run:
          name: yarn installing things
          command: yarn install
      - save_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
      - run: # run tests
          name: test
          command: yarn lint
#   lint:
#     docker:
#       - image: circleci/node:12.14.1
#     steps:
#       - restore_cache: # Restores the cached dependency.
#           key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
#       - run:
#           name: Running lint
#           command: yarn lint

# workflows:
#   version: 2
#   lint:
#     jobs:
#       - build
#       - lint